### ISSUE TITLE
Getting Ruby build exit code 16 when trying to add

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [just-the-docs/just-the-docs-template#13]
Repo: https://github.com/cake-tech/cakewallet-guides

Failing commit: https://github.com/cake-tech/cakewallet-guides/commit/412f63bea4a981c5d5e4f37934e9377439b131bc

Failing build: https://github.com/cake-tech/cakewallet-guides/actions/runs/3877739659/jobs/6613109848#step:3:47

To reproduce:

* Click "Use this template"
* Make a new repo
* Add the `jekyll-default-layout` plugin: https://github.com/just-the-docs/just-the-docs-template#adding-a-plugin
* Build using GitHub Actions

```
Error: Error: The process '/opt/hostedtoolcache/Ruby/3.1.3/x64/bin/bundle' failed with exit code 16
    at ExecState._setResult (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:5381:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:5364:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:5258:27)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:390:28)
    at Pipe.<anonymous> (node:net:687:12)
```

**Comment by mattxwang** [comment]
Hi @SamsungGalaxyPlayer, thanks for submitting an issue. Looking at the build log,

>   You are trying to install in deployment mode after changing your Gemfile. Run `bundle install` elsewhere and add the updated Gemfile.lock to version control.

After adding the gem to your `Gemfile`, you also need to re-run `bundle install` to update the lockfile. The error is from a discrepancy between your `Gemfile` and `Gemfile.lock`.

Let me know if that resolves your issue!

**Comment by SamsungGalaxyPlayer** [comment]
How do I run this with GitHub Actions? Do I need to add the command to the actions script somewhere?

**Comment by mattxwang** [comment]
You don't; you run it locally, and then commit the update to `Gemfile.lock` to your repository.

Perhaps that's something we can make more clear in documentation!

**Comment by SamsungGalaxyPlayer** [comment]
Okay, I didn't realize a command needed to be run locally. `bundle install` run locally fixed the issue.
