### ISSUE TITLE
Jekyll cant seem to install just-the-docs

### ISSUE THREAD

**Issue by jeremytanjianle** [just-the-docs/just-the-docs-template#20]
Hi there,

Experiencing build fails because of this error. 
As a complete beginner at both github actions and jekyll, is there a fix to get passing builds?

Thanks again.

![image](https://user-images.githubusercontent.com/28703546/233778041-c5c15cd0-1073-4b2c-a097-b9bd5b5fd92c.png)

**Comment by mattxwang** [comment]
Hi @jeremytanjianle, thanks for submitting an issue!

To confirm, is this [jeremytanjianle.github.io](https://github.com/jeremytanjianle/jeremytanjianle.github.io)?

It seems like it's working as intended. I'm noticing that you have two concurrent build actions happening, and the one that's failing is the `github-pages` gem (which you're not using) - perhaps you need to explicitly enable GH Pages to build from actions. Do you want to take a look at this issue and see if it resolves your problem? https://github.com/just-the-docs/just-the-docs-template/issues/17#issuecomment-1489754680

**Comment by jeremytanjianle** [comment]
Oh it works, thanks for your patience.

**Comment by themarquee** [comment]
This tripped me up as well. Thanks for the fix and for the awesome theme!
