### ISSUE TITLE
The just-the-docs theme could not be found

### ISSUE THREAD

**Issue by alidehkhodaei** [just-the-docs/just-the-docs-template#21]
I am encountering an error with the "just-the-docs" theme while using the configuration file located at "/github/workspace/./_config.yml". Despite not having made any changes to the "just-the-theme" present in the config file, I am still receiving the following error message:

"Error: The just-the-docs theme could not be found."

I am hoping that someone can assist me in resolving this issue so that I may proceed with my work.

Thank you in advance for your help.

**Comment by mattxwang** [comment]
Hi @alidehkhodaei, thanks for submitting an issue. Can you please provide more information to help you debug? Ex a repo link, etc. Right now there isn't enough information to debug.

**Comment by alidehkhodaei** [comment]
Hello again @mattxwang. This is my repository link.
https://github.com/Developers0101/notes-android-course

**Comment by alidehkhodaei** [comment]
Where is that? It build and deploy has work but show ❌ in every commit.

**Comment by mattxwang** [comment]
There are two parallel builds you have in your CI:

- the default `github-pages` action, which [is the one failing](https://github.com/Developers0101/notes-android-course/actions/runs/4715526861/jobs/8362574477)
- the one packaged with this theme, [which is succeeding](https://github.com/Developers0101/notes-android-course/actions/runs/4715526915)

In fact, there's a deployed version of your site: https://developers0101.github.io/notes-android-course/

To disable the failing action, you should go into your repo settings and change the default build source to Actions (this is under the "pages" section).
