### ISSUE TITLE
just the docs update request

### ISSUE THREAD

**Issue by IzatheWriter** [just-the-docs/just-the-docs-template#44]
Hi,

A few weeks ago I received an e-mail from dependabot asking me a pull request for the just-the-docs template. I am a beginner user of the GitHub and other sites like this so I wasn't sure what I should do.
I am currently working in a site using just-the-docs template. I created a new one but there are some deploy and build problems and then I realized it might be because of the new version of the template. My question is: do I need a new pull request for this repository or since I'm using a template, it should be working since I created it after the updates?

Kind regards,
IzatheWriter

**Comment by mattxwang** [comment]
Hi @IzatheWriter, thanks for submitting an issue! Took a quick look - I'm assuming this is your Beginner Baker's Guide repo? If so, your build is succeeding, i.e. see https://izathewriter.github.io/Beginner-Baker-s-Guide/ 

I think what's happening is that you have two different build-and-deploy jobs going on - one from the GitHub Actions workflow and one from the "pages" gem. If you select "GitHub Actions" as your build source (Settings > Pages > Build and deployment > Source, and select GitHub Actions), future commits should not have this problem.

**Comment by IzatheWriter** [comment]
Thank you SO much for you help @mattxwang!  I REALLY APPRECIATE it! 
I found the right settings which you mentioned and I hope things are going to be okay now. 
Have a great day!
IzatheWriter

**Comment by mattxwang** [comment]
> Thank you SO much for you help @mattxwang! I REALLY APPRECIATE it! I found the right settings which you mentioned and I hope things are going to be okay now. Have a great day! IzatheWriter

Glad to help!
