### ISSUE TITLE
Can't get my just-the-docs site running on Azure Static Websites

### ISSUE THREAD

**Issue by Tom-H2oThermo** [just-the-docs/just-the-docs-template#47]
I'm trying to transition from hosting my website on Azure instead of GitHub Pages.  It looks beautiful on GitHub Pages but terrible on Azure (see the attached images).  I followed these instructions on Learn Microsoft to set up the Azure website: https://learn.microsoft.com/en-us/azure/static-web-apps/publish-jekyll
Then I added all my markdown files to my repository.  I've been comparing the files between the two repositories and the main differences I've found are in the gemfile.lock files, but I don't know if this is the issue.

**Just-the-docs gemfile.lock template:**

    google-protobuf (4.26.1-arm64-darwin)
      rake (>= 13)
    google-protobuf (4.26.1-x86_64-linux)
      rake (>= 13)

PLATFORMS
  arm64-darwin
  x86_64-linux-gnu

DEPENDENCIES
  jekyll (~> 4.3.3)
  just-the-docs (= 0.8.2)

BUNDLED WITH
   2.5.9

**In my current gemfile.lock  file I see these differences.**

    google-protobuf (4.26.1-x64-mingw-ucrt)
      rake (>= 13)
    google-protobuf (4.26.1-x86_64-linux)
      rake (>= 13)
 
   jekyll-feed (0.17.0)
      jekyll (>= 3.7, < 5.0)

    tzinfo (2.0.6)
      concurrent-ruby (~> 1.0)
    tzinfo-data (1.2024.1)
      tzinfo (>= 1.0.0)

PLATFORMS
  ruby
  x64-mingw-ucrt
  x86_64-linux

DEPENDENCIES
  http_parser.rb (~> 0.6.0)
  jekyll-feed (~> 0.12)
  just-the-docs
  tzinfo (>= 1, < 3)
  tzinfo-data
  wdm (~> 0.1.1)

BUNDLED WITH
   2.4.22

Note that if I try to use Bundler 2.5.9 it doesn't seem to like it.  It has dependency conflicts.

My github site is https://github.com/Tom-H2oThermo/jekyll-azure-static

Thank you for any advice you can give me.

<img width="345" alt="Website on Azure" src="https://github.com/just-the-docs/just-the-docs-template/assets/25697066/7245ee59-95c6-4ab8-be27-fddac4ec53c5">
<img width="758" alt="website on github pages" src="https://github.com/just-the-docs/just-the-docs-template/assets/25697066/56afc49e-1e51-4900-931d-1c16255df320">

**Comment by mattxwang** [comment]
Hi @Tom-H2oThermo, thanks for making an issue. Admittedly, I am not familiar with Azure static websites. Would you be able to provide more context (ideally, some sort of source code / repository) to help us debug?

Looking at what you've provided, it seems like the CSS (and likely, other assets, including JS) have not been loaded properly. If you've only faced these issues on Azure, my guess is that there are some issues with the relative or absolute paths to your URLs. That could be a place to start debugging!

**Comment by Tom-H2oThermo** [comment]
Sorry, I should have closed this.  I got this working over the weekend.  Instead of following the Learn Microsoft instructions to the letter, I tried to just wing it.

**Comment by mattxwang** [comment]
Thanks for the quick response @Tom-H2oThermo, and no apologies necessary - glad that it works (and that you're enjoying the theme)!
