### ISSUE TITLE
How to remove the .html suffix?

### ISSUE THREAD

**Issue by abcpeak** [just-the-docs/just-the-docs-template#58]
I see that the URL for the case is https://just-the-docs.com/docs/search, ends with "/search/", but when I place the same file in my repo, it ends with "/search.html". 
How can I remove the .html suffix to make it the same as the case? I've been studying it for half a day and still can't figure it out!

**Comment by mattxwang** [comment]
Hi @abcpeak, thanks for asking. It sounds like you're looking for the [`permalink: pretty` Jekyll option](https://jekyllrb.com/docs/permalinks/#built-in-formats), which you can add to your `_config.yml`.

(alternatively, you can set the `permalink` individually on each page)

Let me know if that doesn't solve your problem!
