### ISSUE TITLE
[Git Action] Build with Jekyll Failed

### ISSUE THREAD

**Issue by Mieekaserra** [just-the-docs/just-the-docs-template#6]
On my repo - brand new no changes https://github.com/Mieekaserra/Mieekaserra.github.io

Am getting the following error

![image](https://user-images.githubusercontent.com/26418143/203831578-aef7742e-62ea-412a-a76c-39431ee9fe57.png)

Which gives me the following error.
/usr/bin/docker run --name ghcrioactionsjekyllbuildpagesv106_b31546 --label 290506 --workdir /github/workspace --rm -e "INPUT_SOURCE" -e "INPUT_DESTINATION" -e "INPUT_FUTURE" -e "INPUT_BUILD_REVISION" -e "INPUT_VERBOSE" -e "INPUT_TOKEN" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_ID_TOKEN_REQUEST_URL" -e "ACTIONS_ID_TOKEN_REQUEST_TOKEN" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/Mieekaserra.github.io/Mieekaserra.github.io":"/github/workspace" ghcr.io/actions/jekyll-build-pages:v1.0.6
/usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/theme.rb:84:in `rescue in gemspec': The just-the-docs theme could not be found. (Jekyll::Errors::MissingDependencyException)
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/theme.rb:81:in `gemspec'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/theme.rb:19:in `root'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/theme.rb:12:in `initialize'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:439:in `new'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:439:in `configure_theme'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:55:in `config='
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:23:in `initialize'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:30:in `new'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:30:in `process'
	from /usr/local/bundle/gems/github-pages-227/bin/github-pages:70:in `block (3 levels) in <top (required)>'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /usr/local/bundle/gems/github-pages-227/bin/github-pages:6:in `<top (required)>'
	from /usr/local/bundle/bin/github-pages:23:in `load'
	from /usr/local/bundle/bin/github-pages:23:in `<main>'
/usr/local/lib/ruby/2.7.0/rubygems/dependency.rb:3[11](https://github.com/Mieekaserra/Mieekaserra.github.io/actions/runs/3542179945/jobs/5947366955#step:4:12):in `to_specs': Could not find 'just-the-docs' (>= 0) among 148 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/github/home/.gem/ruby/2.7.0:/usr/local/lib/ruby/gems/2.7.0:/usr/local/bundle', execute `gem env` for more information
	from /usr/local/lib/ruby/2.7.0/rubygems/dependency.rb:323:in `to_spec'
	from /usr/local/lib/ruby/2.7.0/rubygems/specification.rb:986:in `find_by_name'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/theme.rb:82:in `gemspec'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/theme.rb:19:in `root'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/theme.rb:[12](https://github.com/Mieekaserra/Mieekaserra.github.io/actions/runs/3542179945/jobs/5947366955#step:4:13):in `initialize'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:439:in `new'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:439:in `configure_theme'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:55:in `config='
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:23:in `initialize'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:30:in `new'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:30:in `process'
	from /usr/local/bundle/gems/github-pages-227/bin/github-pages:70:in `block (3 levels) in <top (required)>'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:[19](https://github.com/Mieekaserra/Mieekaserra.github.io/actions/runs/3542179945/jobs/5947366955#step:4:20):in `program'
	from /usr/local/bundle/gems/github-pages-[22](https://github.com/Mieekaserra/Mieekaserra.github.io/actions/runs/3542179945/jobs/5947366955#step:4:23)7/bin/github-pages:6:in `<top (required)>'
	from /usr/local/bundle/bin/github-pages:[23](https://github.com/Mieekaserra/Mieekaserra.github.io/actions/runs/3542179945/jobs/5947366955#step:4:24):in `load'
	from /usr/local/bundle/bin/github-pages:23:in `<main>'
  Logging at level: debug
Configuration file: /github/workspace/./_config.yml
             Theme: just-the-docs
github-pages 2[27](https://github.com/Mieekaserra/Mieekaserra.github.io/actions/runs/3542179945/jobs/5947366955#step:4:28) | Error:  The just-the-docs theme could not be found.

**Comment by mattxwang** [comment]
Hi @Mieekaserra, thanks for submitting this issue. I think I need a bit more context; two questions:

1. Did you enable deploying from Actions? I'm not sure why the `github-pages` gem is being loaded into your space. You need to do this in your settings. In particular, you **should not use the default github pages build**: you should be "building /deploying from actions".
    - perhaps we can document this better!
2. It seems like something exists at [Mieekaserra.github.io](https://github.com/Mieekaserra/Mieekaserra.github.io), so at least one of the builds succeeded. What was the diff you made that introduced the error?

**Comment by Mieekaserra** [comment]
Nothing - Its been failing since i setup the template.

**Comment by mattxwang** [comment]
No worries, just makes it a bit harder to troubleshoot. Looks like you resolved it in https://github.com/Mieekaserra/Mieekaserra.github.io/commit/6145faa5c9d4f97dd74ae35d7ef88a5be1b9a38b by using a remote theme.

I'm going to close this issue for now, since your direct problem was resolved, but it sounds like we can do a better job documenting the template / testing it. I'll take this up over the next few days; if you have any suggestions or are willing to submit a PR, that would be appreciated.

**Comment by mattxwang** [comment]
Hey @Mieekaserra, just following up - tried to repro with this repository and couldn't repro: https://github.com/mattxwang/test-jtd-bug

What were the exact steps you did? For reference, I did:

1. use template to create repo
2. settings -> select "github actions" for pages deploy
3. build works
4. make arbitrary commit touching `index.md`
5. build still works
